import Head from 'next/head'
import DetailTemplate from '@/components/templates/DetailTemplate'



export const getServerSideProps = () => {
    return {
        
    }
}

export default function StoreDetail() {

  return (
    <>
      <Head>
        <title>행마니</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DetailTemplate />
    </>
  )
}
