import Head from 'next/head'
import styled from '@emotion/styled'
import GridMain from '@/components/templates/GridMain'
import { useEffect, useState } from 'react'



export default function Home() {
  const [text, setText] = useState<string>('헬로');

  useEffect(() => {
    setText('머함?')
    console.log(text)
  }, [])

  return (
    <>
      <Head>
        <title>행마니</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GridMain />
      {text}
      야 왜 이거 안나와?
    </>
  )
}
