import Head from 'next/head'
import MainTemplate from '@/components/templates/MainTemplate'
import { ReactElement, ReactNode } from 'react'
import Layout from '@/components/layouts/Layout'
import MapLayout from '@/components/layouts/MapLayout'


export default function Map() {

  return (
    <>
      <Head>
        <title>행마니</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}



Map.getLayout = (page: ReactElement) => {
    return <MapLayout>{page}</MapLayout>
}